package(
    default_visibility = [
        "//cmd/server:__subpackages__",
    ],
)

alias(
    name = "option",
    actual = "@org_golang_google_api//option:go_default_library",
)

alias(
    name = "iterator",
    actual = "@org_golang_google_api//iterator:go_default_library",
)
