package(
    default_visibility = [
        "//pkg/protocol:__subpackages__",
    ],
)

alias(
    name = "grpc",
    actual = "@org_golang_google_grpc//:go_default_library",
)

alias(
    name = "grpc_credentials",
    actual = "@org_golang_google_grpc//credentials",
)

alias(
    name = "grpc_credentials_insecure",
    actual = "@org_golang_google_grpc//credentials/insecure",
)

alias(
    name = "grpc_metadata",
    actual = "@org_golang_google_grpc//metadata",
)

alias(
    name = "grpc_codes",
    actual = "@org_golang_google_grpc//codes",
)

alias(
    name = "grpc_status",
    actual = "@org_golang_google_grpc//status",
)